# SECURITY WARNING: ALLOWED_HOSTS !
ALLOWED_HOSTS = []

# SECURITY WARNING: CSRF_TRUSTED_ORIGINS !
CSRF_TRUSTED_ORIGINS = []

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True