# REPLACE WITH YOU'R VARIABLES
DJANGO_HOST="0.0.0.0"
DJANGO_PORT=8080
SECRET_KEY="YOUR_DJANGO_SECURIRY_CODE_PASTE_HERE"
TELEGRAM_BOT_API_TOKEN="YOUR_TELEGRAM_API_TOKEN_HERE"
kavenegar_api_key="YOUR_SMS_API_KAY_PASTE_HERE"