# Generated by Django 5.0.7 on 2024-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کار')),
                ('jobStatus', models.CharField(blank=True, max_length=40, null=True, verbose_name='وضعیت کار')),
                ('lastjob', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین کار')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار ها',
            },
        ),
    ]
