# Generated by Django 5.0.7 on 2024-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='jobArg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آرگومان کار'),
        ),
    ]
