# Generated by Django 5.0.6 on 2024-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='send_status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='وضعیت ارسال'),
        ),
    ]
