# Generated by Django 5.0.7 on 2024-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='هدف')),
                ('siteMapUrl', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سایت مپ',
                'verbose_name_plural': 'سایت مپ ها',
            },
        ),
    ]
