# Generated by Django 5.0.7 on 2024-07-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_parent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس محصول'),
        ),
    ]
