# Generated by Django 5.0.7 on 2024-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_parent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سایت والد'),
        ),
    ]
