# Generated by Django 5.0.7 on 2024-07-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product_status_product_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_product_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='کلید')),
                ('us_product_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام')),
                ('us_product_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت')),
                ('us_product_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت محصول تحت نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول تحت نظر',
                'verbose_name_plural': 'محصولات تحت نظر',
            },
        ),
    ]
