# Generated by Django 5.0.6 on 2024-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_botusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت نام'),
        ),
        migrations.AddField(
            model_name='botusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
